version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=verosabeauty;User=root;Password=your_password;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: verosabeauty
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: